import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/navigation/Header";
import Footer from "@/components/navigation/Footer";
import { Dock } from "@/components/Dock";


export const metadata: Metadata = {
  title: "digital artisan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body >
        <Header />
        {children}
        <div className={'fixed bottom-0 left-1/2 translate-x-[-50%]'}>
          <Dock />
        </div>
        {/*<Footer/>*/}
      </body>
    </html>
  );
}
