import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/navigation/Header";


export const metadata: Metadata = {
  title: "Slide Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <Header />

        {children}</body>
    </html>
  );
}
