import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/navigation/Header";
import Footer from "@/components/navigation/Footer";


export const metadata: Metadata = {
  title: "shift agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
